project_tracker/project_tracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tasks/', include('tasks.urls')),
    path('quality_control/', include('quality_control.urls')),
]

project_tracker/quality_control/urls.py
from django.urls import path
from quality_control import views

app_name = 'quality_control'

urlpatterns = [
    path('', views.index, name='index'),

    path('bugs/', views.bug_list, name='bug_list'),
    path('features/', views.feature_list, name='feature_list'),
    path('bugs/<int:bug_id>/', views.bug_detail, name='bug_detail'),
    path('features/<int:feature_id>/', views.feature_detail, name='feature_detail'),
    path('bugs/new/', views.create_bug_report, name='create_bug_report'),
    path('features/new/', views.create_feature_request, name='create_feature_request'),
    path('bugs/<int:bug_id>/update/', views.update_bug, name='update_bug'),
    path('features/<int:feature_id>/update/', views.update_feature, name='update_feature'),
    path('bugs/<int:bug_id>/delete/', views.delete_bug, name='delete_bug'),
    path('features/<int:feature_id>/delete/', views.delete_feature, name='delete_feature'),

    # path('bugs/', views.BugListView.as_view(), name='bug_list'),
    # path('features/', views.FeatureListView.as_view(), name='feature_list'),
    # path('bugs/<int:bug_id>/', views.BugDetailView.as_view(), name='bug_detail'),
    # path('features/<int:feature_id>/', views.FeatureDetailView.as_view(), name='feature_detail'),
    # path('bugs/new/', views.BugReportCreateView.as_view(), name='create_bug_report'),
    # path('features/new/', views.FeatureRequestCreateView.as_view(), name='create_feature_request'),
    # path('bugs/<int:bug_id>/update/', views.BugReportUpdateView.as_view(), name='update_bug'),
    # path('bugs/<int:feature_id>/update/', views.FeatureRequestUpdateView.as_view(), name='update_feature'),
    # path('bugs/<int:bug_id>/delete/', views.BugReportDeleteView.as_view(), name='delete_bug'),
    # path('features/<int:feature_id>/delete/', views.FeatureRequestDeleteView.as_view(), name='delete_feature'),
]

project_tracker/tasks/urls.py
from django.urls import path
from tasks import views

app_name = 'tasks'

urlpatterns = [
    path('', views.index, name='index'),
    path('projects/', views.projects_list, name='projects_list'),
    path('projects/<int:project_id>/', views.project_detail, name='project_detail'),
    path('projects/<int:project_id>/tasks/<int:task_id>/', views.task_detail, name='task_detail'),
    path('feedback/', views.feedback_view, name='feedback'),
    path('project/new/', views.create_project, name='create_project'),
    # path('project/<int:project_id>/add_task/', views.add_task_to_project, name='add_task_to_project'),
    path('project/create/', views.ProjectCreateView.as_view(), name='create_project'),
    path('project/<int:project_id>/add_task/', views.TaskCreateView.as_view(), name='add_task_to_project'),
    # path('project/<int:project_id>/update/', views.update_project, name='update_project'),
    # path('project/<int:project_id>/task/<int:task_id>/update/', views.update_task, name='update_task'),
    path('project/<int:project_id>/update/', views.ProjectUpdateView.as_view(), name='update_project'),
    path('project/<int:project_id>/tasks/<int:task_id>/update/', views.TaskUpdateView.as_view(), name='update_task'),
    # path('project/<int:project_id>/delete/', views.delete_project, name='delete_project'),
    # path('project/<int:project_id>/tasks/<int:task_id>/delete/', views.delete_task, name='delete_task'),
    path('project/<int:project_id>/delete/', views.ProjectDeleteView.as_view(), name='delete_project'),
    path('project/<int:project_id>/tasks/<int:task_id>/delete/', views.TaskDeleteView.as_view(), name='delete_task'),
    # path('', views.IndexView.as_view(), name='index'),
    # path('projects/', views.ProjectsListView.as_view(), name='projects_list'),
    # path('projects/<int:project_id>/', views.ProjectDetailView.as_view(), name='project_detail'),
    # path('projects/<int:project_id>/tasks/<int:task_id>/', views.TaskDetailView.as_view(), name='task_detail'),
]

project_tracker/quality_control/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from tasks.models import Project, Task

# Create your models here.

class BugReport(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    project = models.ForeignKey(
        Project,
        on_delete=models.CASCADE
    )
    task = models.ForeignKey(
        Task,
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )
    STATUS_CHOICES = [
        ('New', 'Новый'),
        ('In_progress', 'В работе'),
        ('Completed', 'Завершен'),
    ]
    status = models.CharField(
        max_length=50,
        choices=STATUS_CHOICES,
        default='New',
    )
    # priority = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    PRIORITY_CHOICES = [
        (1, 'Очень низкий'),
        (2, 'Низкий'),
        (3, 'Средний'),
        (4, 'Высокий'),
        (5, 'Крайне высокий'),
    ]
    priority = models.IntegerField(
        choices=PRIORITY_CHOICES,
        default=3,
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class FeatureRequest(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    project = models.ForeignKey(
        Project,
        on_delete=models.CASCADE
    )
    task = models.ForeignKey(
        Task,
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )
    STATUS_CHOICES = [
        ('Consideration', 'Рассмотрение'),
        ('Accepted', 'Принято'),
        ('Rejected', 'Отклонено'),
    ]
    status = models.CharField(
        max_length=50,
        choices=STATUS_CHOICES,
        default='Consideration',
    )
    # priority = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    PRIORITY_CHOICES = [
        (1, 'Очень низкий'),
        (2, 'Низкий'),
        (3, 'Средний'),
        (4, 'Высокий'),
        (5, 'Крайне высокий'),
    ]
    priority = models.IntegerField(
        choices=PRIORITY_CHOICES,
        default=3,
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

project_tracker/quality_control/forms.py
from django.forms import ModelForm
from .models import BugReport, FeatureRequest

class BugReportForm(ModelForm):
    class Meta:
        model = BugReport
        fields = ['title', 'description', 'status', 'priority', 'project', 'task']

class FeatureRequestForm(ModelForm):
    class Meta:
        model = FeatureRequest
        fields = ['title', 'description', 'status', 'priority', 'project', 'task']

project_tracker/quality_control/views.py
# from django.http import HttpResponse
# from django.views import View
from django.urls import reverse_lazy #, reverse
from .models import BugReport, FeatureRequest
from django.views.generic import DetailView, CreateView, ListView, UpdateView, DeleteView
from django.shortcuts import get_object_or_404, render, redirect
from .forms import BugReportForm, FeatureRequestForm

# def index(request):
#     bug_list_url = reverse('quality_control:bug_list')
#     feature_list_url = reverse('quality_control:feature_list')
#     html = f'''<h1>Система контроля качества</h1><a href='{bug_list_url}'>Список всех багов</a></br>
#         <a href='{feature_list_url}'>Запросы на улучшение</a>'''
#     return HttpResponse(html)

# class IndexView(View):
#     def get(self, request, *args, **kwargs):
#         bug_list_url = reverse('quality_control:bug_list')
#         feature_list_url = reverse('quality_control:feature_list')
#         html = f'''<h1>Система контроля качества</h1><a href='{bug_list_url}'>Список всех багов</a></br>
#             <a href='{feature_list_url}'>Запросы на улучшение</a>'''
#         return HttpResponse(html)
    
def index(request):
    return render(request, 'quality_control/index.html')

# def bug_list(request):
#     bugs = BugReport.objects.all()
#     bugs_html = '<h1>Список отчетов об ошибках</h1><ul>'
#     for bug in bugs:
#         bugs_html += f'<li><a href="{bug.id}/">{bug.title}</a> - {bug.status}</li>'
#     bugs_html += '</ul>'
#     return HttpResponse(bugs_html)

def bug_list(request):
    bugs = BugReport.objects.all()
    return render(request, 'quality_control/bug_list.html', {'bug_list': bugs})

class BugListView(ListView):
    model = BugReport
    template_name = 'quality_control/bug_list.html'

# class BugDetailView(DetailView):
#     model = BugReport
#     pk_url_kwarg = 'bug_id'

#     def get(self, request, *args, **kwargs):
#         self.object = self.get_object()
#         bug = self.object
#         response_html = f'<h1>{bug.title}</h1><p>{bug.description}</p>'
#         response_html += f'<p>Статус: {bug.status}</p>'
#         response_html += f'<p>Приоритет: {bug.priority}</p>'
#         project_detail_url = reverse('tasks:project_detail', kwargs={'project_id': bug.project.id})
#         response_html += f'<p>Проект: <a href="{project_detail_url}">{bug.project.name}</a></p>'
#         task_detail_url = reverse('tasks:task_detail', kwargs={'project_id': bug.project.id, 'task_id': bug.task.id})
#         response_html += f'<p>Задача: <a href="{task_detail_url}">{bug.task.name}</a></p>'
#         return HttpResponse(response_html)

def bug_detail(request, bug_id):
    bug = get_object_or_404(BugReport, id=bug_id)
    return render(request, 'quality_control/bug_detail.html', {'bugreport': bug})

class BugDetailView(DetailView):
    model = BugReport
    pk_url_kwarg = 'bug_id'
    template_name = 'quality_control/bug_detail.html'

# def feature_list(request):
#     features = FeatureRequest.objects.all()
#     features_html = '<h1>Список запросов на улучшение</h1><ul>'
#     for feature in features:
#         features_html += f'<li><a href="{feature.id}/">{feature.title}</a> - {feature.status}</li>'
#     features_html += '</ul>'
#     return HttpResponse(features_html)

def feature_list(request):
    features = FeatureRequest.objects.all()
    return render(request, 'quality_control/feature_list.html', {'feature_list': features})

class FeatureListView(ListView):
    model = FeatureRequest
    template_name = 'quality_control/feature_list.html'

# class FeatureDetailView(DetailView):
#     model = FeatureRequest
#     pk_url_kwarg = 'feature_id'

#     def get(self, request, *args, **kwargs):
#         self.object = self.get_object()
#         feature = self.object
#         response_html = f'<h1>{feature.title}</h1><p>{feature.description}</p>'
#         response_html += f'<p>Статус: {feature.status}</p>'
#         response_html += f'<p>Приоритет: {feature.priority}</p>'
#         project_detail_url = reverse('tasks:project_detail', kwargs={'project_id': feature.project.id})
#         response_html += f'<p>Проект: <a href="{project_detail_url}">{feature.project.name}</a></p>'
#         task_detail_url = reverse('tasks:task_detail', kwargs={'project_id': feature.project.id, 'task_id': feature.task.id})
#         response_html += f'<p>Задача: <a href="{task_detail_url}">{feature.task.name}</a></p>'
#         return HttpResponse(response_html)

def feature_detail(request, feature_id):
    feature = get_object_or_404(FeatureRequest, id=feature_id)
    return render(request, 'quality_control/feature_detail.html', {'featurerequest': feature})

class FeatureDetailView(DetailView):
    model = FeatureRequest
    pk_url_kwarg = 'feature_id'
    template_name = 'quality_control/feature_detail.html'

# def bug_detail(request, bug_id):
#     return HttpResponse(f"<h1>Детали бага {bug_id}</h1>")

# def feature_id_detail(request, feature_id):
#     return HttpResponse(f"<h1>Детали улучшения {feature_id}</h1>")

def create_bug_report(request):
    if request.method == 'POST':
        form = BugReportForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('quality_control:bug_list')
    else:
        form = BugReportForm()
    return render(request, 'quality_control/bug_report_form.html', {'form': form})

class BugReportCreateView(CreateView):
    model = BugReport
    form_class = BugReportForm
    template_name = 'quality_control/bug_report_form.html'
    success_url = reverse_lazy('quality_control:bug_list')

def create_feature_request(request):
    if request.method == 'POST':
        form = FeatureRequestForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('quality_control:feature_list')
    else:
        form = FeatureRequestForm()
    return render(request, 'quality_control/feature_request_form.html', {'form': form})

class FeatureRequestCreateView(CreateView):
    model = FeatureRequest
    form_class = FeatureRequestForm
    template_name = 'quality_control/feature_request_form.html'
    success_url = reverse_lazy('quality_control:feature_list')

def update_bug(request, bug_id):
    bug = get_object_or_404(BugReport, pk=bug_id)
    if request.method == 'POST':
        form = BugReportForm(request.POST, instance=bug)
        if form.is_valid():
            form.save()
            return redirect('quality_control:bug_detail', bug_id=bug.id)
    else:
        form = BugReportForm(instance=bug)
    return render(request, 'quality_control/bug_update.html', {'form': form, 'bug': bug})

def update_feature(request, feature_id):
    feature = get_object_or_404(FeatureRequest, pk=feature_id)
    if request.method == 'POST':
        form = FeatureRequestForm(request.POST, instance=feature)
        if form.is_valid():
            form.save()
            return redirect('quality_control:feature_detail', feature_id=feature.id)
    else:
        form = FeatureRequestForm(instance=feature)
    return render(request, 'quality_control/feature_update.html', {'form': form, 'feature': feature})

class BugReportUpdateView(UpdateView):
    model = BugReport
    form_class = BugReportForm
    template_name = 'quality_control/bug_update.html'
    pk_url_kwarg = 'bug_id'
    # success_url = reverse_lazy('quality_control:bug_list')

    def get_success_url(self):
        return reverse_lazy('quality_control:bug_detail', kwargs={'bug_id': self.object.id})

class FeatureRequestUpdateView(UpdateView):
    model = FeatureRequest
    form_class = FeatureRequestForm
    template_name = 'quality_control/feature_update.html'
    pk_url_kwarg = 'feature_id'
    # success_url = reverse_lazy('quality_control:feature_list')

    def get_success_url(self):
        return reverse_lazy('quality_control:feature_detail', kwargs={'feature_id': self.object.id})

def delete_bug(request, bug_id):
    bug = get_object_or_404(BugReport, pk=bug_id)
    bug.delete()
    return redirect('quality_control:bug_list')

def delete_feature(request, feature_id):
    feature = get_object_or_404(FeatureRequest, pk=feature_id)
    feature.delete()
    return redirect('quality_control:feature_list')

class BugReportDeleteView(DeleteView):
    model = BugReport
    pk_url_kwarg = 'bug_id'

    def get_success_url(self):
        return reverse_lazy('quality_control:bug_detail', kwargs={'bug_id': self.object.id})
    
class FeatureRequestDeleteView(DeleteView):
    model = FeatureRequest
    pk_url_kwarg = 'feature_id'

    def get_success_url(self):
        return reverse_lazy('quality_control:feature_detail', kwargs={'feature_id': self.object.id})

project_tracker/quality_control/templates/quality_control/bug_detail.html
{% extends 'base/base.html' %}

{% block content %}
    <p><a href="{% url 'quality_control:update_bug' bugreport.id %}">Изменить отчет</a></p>
    <p><a href="{% url 'quality_control:delete_bug' bugreport.id %}"onclick="return confirm('Вы уверены, что хотите удалить этот отчет об ошибке?');">Удалить отчет об ошибке</a></p>
    <h1>{{ bugreport.title }}</h1>
    <p>{{ bugreport.description }}</p>
    <p>Статус: {{ bugreport.status }}</p>
    <p>Приоритет: {{ bugreport.priority }}</p>
    <p>Проект: <a href="{% url 'tasks:project_detail' bugreport.project.id %}">{{ bugreport.project.name }}</a></p>
    {% if bugreport.task %}
        <p>Задача: <a href="{% url 'tasks:task_detail' bugreport.project.id bugreport.task.id %}">{{ bugreport.task.name }}</a></p>
    {% endif %}
{% endblock %}

project_tracker/quality_control/templates/quality_control/bug_list.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Список отчетов об ошибках</h1>
    <p><a href="{% url 'quality_control:create_bug_report' %}">Создать новый отчет об ошибке</a></p>
    <ul>
        {% for bug in BugReport.object.all %}
            <li><a href="{% url 'quality_control:bug_detail' bug.id %}">{{ bug.title }}</a> - {{ bug.status }}</li>
        {% endfor %}
    </ul>
{% endblock %}

project_tracker/quality_control/templates/quality_control/bug_report_form.html
{% extends 'base/base.html' %}

{% block content %}
    <h2>Создать новый отчет об ошибке</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Создать отчет</button>
    </form>
{% endblock %}

project_tracker/quality_control/templates/quality_control/bug_update.html
{% extends 'base/base.html' %}

{% block content %}
<h2>Изменение отчета об ошибке: {{ bug.title }}</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Сохранить</button>
    </form>
{% endblock %}

project_tracker/quality_control/templates/quality_control/bugreport_confirm_delete.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Удаление отчета об ошибке</h1>
    <p>Вы уверены, что хотите удалить отчет об ошибке "{{ bugreport.title }}"?</p>

    <form action="{% url 'quality_control:delete_bug' bugreport.id %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Удалить">
        <a href="{% url 'quality_control:bug_detail' bugreport.id %}">Отмена</a>
    </form>
{% endblock %}

project_tracker/quality_control/templates/quality_control/feature_detail.html
{% extends 'base/base.html' %}

{% block content %}
    <p><a href="{% url 'quality_control:update_feature' featurerequest.id %}">Изменить запрос</a></p>
    <p><a href="{% url 'quality_control:delete_feature' featurerequest.id %}"onclick="return confirm('Вы уверены, что хотите удалить этот запрос на улучшение?');">Удалить запрос на улучшение</a></p>
    <h1>{{ featurerequest.title }}</h1>
    <p>{{ featurerequest.description }}</p>
    <p>Статус: {{ featurerequest.status }}</p>
    <p>Приоритет: {{ featurerequest.priority }}</p>
    <p>Проект: <a href="{% url 'tasks:project_detail' featurerequest.project.id %}">{{ featurerequest.project.name }}</a></p>
    {% if featurerequest.task %}
        <p>Задача: <a href="{% url 'tasks:task_detail' featurerequest.project.id featurerequest.task.id %}">{{ featurerequest.task.name }}</a></p>
    {% endif %}
{% endblock %}

project_tracker/quality_control/templates/quality_control/feature_list.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Список запросов на улучшение</h1>
    <p><a href="{% url 'quality_control:create_feature_request' %}">Создать новый запрос на улучшение</a></p>
    <ul>
        {% for feature in feature_list %}
            <li><a href="{% url 'quality_control:feature_detail' feature.id %}">{{ feature.title }}</a> - {{ feature.status }}</li>
        {% endfor %}
    </ul>
{% endblock %}

project_tracker/quality_control/templates/quality_control/feature_request_form.html
{% extends 'base/base.html' %}

{% block content %}
    <h2>Создать новый запрос на улучшение</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Создать запрос</button>
    </form>
{% endblock %}

project_tracker/quality_control/templates/quality_control/feature_update.html
{% extends 'base/base.html' %}

{% block content %}
<h2>Изменение запроса на улучшение: {{ feature.title }}</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Сохранить</button>
    </form>
{% endblock %}

project_tracker/quality_control/templates/quality_control/featurerequest_confirm_delete.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Удаление запроса на улучшение</h1>
    <p>Вы уверены, что хотите удалить запрос на улучшение "{{ featurerequest.title }}"?</p>

    <form action="{% url 'quality_control:delete_feature' featurerequest.id %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Удалить">
        <a href="{% url 'quality_control:feature_detail' featurerequest.id %}">Отмена</a>
    </form>
{% endblock %}

project_tracker/quality_control/templates/quality_control/index.html
{% extends 'base/base.html' %}

{% block content %}
        <h1>Система контроля качества</h1>
        <a href="{% url 'quality_control:bug_list' %}">Список всех багов</a></br>
        <a href="{% url 'quality_control:feature_list' %}">Запросы на улучшение</a>
{% endblock %}